/**
 * PDF生成モジュール (pdf-lib を使用)
 * Vercel サーバーレス環境で動作する純粋JS実装
 * pdf-lib選定理由: Node.jsネイティブ依存なし・Vercel Edge/Serverless両対応
 */

import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import { createHash } from "crypto";

export interface PdfProjectData {
  projectTitle: string;
  projectDescription: string;
  generatedAt: string;
  voteCount: number;
  supportCount: number;
  reportSummaries: Array<{
    title: string;
    period: string;
    outcomes: string;
  }>;
  stpfLinks: Array<{ from: string; to: string; linkType: string }>;
  timelineSummary: string[];
  auditExcerpts: Array<{ action: string; entityType: string; createdAt: string }>;
  jsonHash: string;
}

export async function generateProjectPdf(
  data: PdfProjectData,
  jsonBytes: Uint8Array
): Promise<Uint8Array> {
  const jsonHash = createHash("sha256").update(jsonBytes).digest("hex");

  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const marginX = 50;
  const pageWidth = 595;
  const pageHeight = 842;
  const lineH = 16;
  let page = pdfDoc.addPage([pageWidth, pageHeight]);
  let y = pageHeight - 60;

  function ensureLine(needed = lineH * 2) {
    if (y - needed < 60) {
      page = pdfDoc.addPage([pageWidth, pageHeight]);
      y = pageHeight - 60;
    }
  }

  function drawText(text: string, size = 10, bold = false, color = rgb(0, 0, 0)) {
    ensureLine(lineH);
    page.drawText(text.substring(0, 90), {
      x: marginX,
      y,
      size,
      font: bold ? boldFont : font,
      color,
    });
    y -= lineH;
  }

  function drawHRule() {
    ensureLine(4);
    page.drawLine({
      start: { x: marginX, y },
      end: { x: pageWidth - marginX, y },
      thickness: 0.5,
      color: rgb(0.5, 0.5, 0.5),
    });
    y -= 8;
  }

  // Header
  drawText("Plato Network — Project Report", 16, true);
  drawText(data.projectTitle, 13, true);
  drawText(`Generated: ${data.generatedAt}`, 9);
  drawHRule();

  // Overview
  drawText("Overview", 12, true);
  drawText(data.projectDescription, 10);
  drawText(`Votes: ${data.voteCount}  |  Supporters: ${data.supportCount}`, 10);
  drawHRule();

  // STPF Links
  if (data.stpfLinks.length > 0) {
    drawText("STPF Causal Links", 12, true);
    for (const link of data.stpfLinks.slice(0, 20)) {
      drawText(`[${link.linkType}] ${link.from} → ${link.to}`, 9);
    }
    drawHRule();
  }

  // Reports
  if (data.reportSummaries.length > 0) {
    drawText("Published Reports", 12, true);
    for (const r of data.reportSummaries.slice(0, 10)) {
      drawText(`${r.title} (${r.period})`, 10, true);
      drawText(r.outcomes.substring(0, 80), 9);
    }
    drawHRule();
  }

  // Timeline summary
  if (data.timelineSummary.length > 0) {
    drawText("Timeline Summary", 12, true);
    for (const entry of data.timelineSummary.slice(0, 15)) {
      drawText(`• ${entry}`, 9);
    }
    drawHRule();
  }

  // Audit excerpts
  if (data.auditExcerpts.length > 0) {
    drawText("Audit Log Excerpts", 12, true);
    for (const a of data.auditExcerpts.slice(0, 20)) {
      drawText(`[${a.createdAt}] ${a.action} on ${a.entityType}`, 9);
    }
    drawHRule();
  }

  // Footer
  drawText(`JSON SHA-256: ${jsonHash}`, 8, false, rgb(0.4, 0.4, 0.4));
  drawText("This document is generated by Plato Network. Audit trail is append-only.", 8, false, rgb(0.4, 0.4, 0.4));

  return await pdfDoc.save();
}
